# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-08 18:06
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TodoItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('duedate', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
