# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-11 11:51
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoitem',
            name='description',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='todoitem',
            name='duedate',
            field=models.DateField(blank=True, default=datetime.date.today),
        ),
    ]
